services:
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./volume/chroma_data:/chroma/chroma
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - IS_PERSISTENT=TRUE

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
    env_file:
      - .env
    volumes:
      - ./volume/sqlite:/app/volume/sqlite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env